version: '3.8'
services:
  paserver-unigui:
    build: .
    container_name: paserver-unigui
    restart: unless-stopped
    environment:
      PA_SERVER_PASSWORD: '1532'
    ports:
      - '64211:64211'
      - '8077:8077'
      - '8082:8082'
      - '8080:8080'
    volumes:
      - './opt:/opt/app'
    tty: true
